/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cmock.h"
#include "rvc.h"
#include "mock_hw_interface.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_check_obstacle_withNoObstacle();
extern void test_check_obstacle_withFrontObstacle();
extern void test_check_obstacle_withLeftObstacle();
extern void test_check_obstacle_withRightObstacle();
extern void test_check_obstacle_withFrontLeftObstacle();
extern void test_check_obstacle_withFrontRightObstacle();
extern void test_check_obstacle_withLeftRightObstacle();
extern void test_check_obstacle_withFrontLeftRightObstacle();
extern void test_check_dust_withNoDust();
extern void test_check_dust_withDust();
extern void test_cleaner_control_withDustWhileMoveForward();
extern void test_cleaner_control_withNoDustWhileMoveForward();
extern void test_motor_control_withNoObstacleWhileMoveForward();
extern void test_motor_control_withLeftRightObstacleWhileMoveForward();
extern void test_motor_control_withFrontLeftRightObstacleWhileMoveForward();
extern void test_motor_control_withFrontLeftObstacleWhileMoveForward();
extern void test_motor_control_withFrontRightObstacleWhileMoveForward();
extern void test_motor_control_withLeftRightObstacleWhileMovebackward();
extern void test_motor_control_withNoLeftRightObstacleWhileMovebackward();
extern void test_motor_control_withNoLeftObstacleWhileMovebackward();
extern void test_motor_control_withNoRightObstacleWhileMovebackward();


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  mock_hw_interface_Init();
}
static void CMock_Verify(void)
{
  mock_hw_interface_Verify();
}
static void CMock_Destroy(void)
{
  mock_hw_interface_Destroy();
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("rvc_unit_test.c");
  run_test(test_check_obstacle_withNoObstacle, "test_check_obstacle_withNoObstacle", 8);
  run_test(test_check_obstacle_withFrontObstacle, "test_check_obstacle_withFrontObstacle", 15);
  run_test(test_check_obstacle_withLeftObstacle, "test_check_obstacle_withLeftObstacle", 22);
  run_test(test_check_obstacle_withRightObstacle, "test_check_obstacle_withRightObstacle", 29);
  run_test(test_check_obstacle_withFrontLeftObstacle, "test_check_obstacle_withFrontLeftObstacle", 36);
  run_test(test_check_obstacle_withFrontRightObstacle, "test_check_obstacle_withFrontRightObstacle", 43);
  run_test(test_check_obstacle_withLeftRightObstacle, "test_check_obstacle_withLeftRightObstacle", 51);
  run_test(test_check_obstacle_withFrontLeftRightObstacle, "test_check_obstacle_withFrontLeftRightObstacle", 58);
  run_test(test_check_dust_withNoDust, "test_check_dust_withNoDust", 65);
  run_test(test_check_dust_withDust, "test_check_dust_withDust", 70);
  run_test(test_cleaner_control_withDustWhileMoveForward, "test_cleaner_control_withDustWhileMoveForward", 75);
  run_test(test_cleaner_control_withNoDustWhileMoveForward, "test_cleaner_control_withNoDustWhileMoveForward", 82);
  run_test(test_motor_control_withNoObstacleWhileMoveForward, "test_motor_control_withNoObstacleWhileMoveForward", 87);
  run_test(test_motor_control_withLeftRightObstacleWhileMoveForward, "test_motor_control_withLeftRightObstacleWhileMoveForward", 93);
  run_test(test_motor_control_withFrontLeftRightObstacleWhileMoveForward, "test_motor_control_withFrontLeftRightObstacleWhileMoveForward", 99);
  run_test(test_motor_control_withFrontLeftObstacleWhileMoveForward, "test_motor_control_withFrontLeftObstacleWhileMoveForward", 108);
  run_test(test_motor_control_withFrontRightObstacleWhileMoveForward, "test_motor_control_withFrontRightObstacleWhileMoveForward", 119);
  run_test(test_motor_control_withLeftRightObstacleWhileMovebackward, "test_motor_control_withLeftRightObstacleWhileMovebackward", 130);
  run_test(test_motor_control_withNoLeftRightObstacleWhileMovebackward, "test_motor_control_withNoLeftRightObstacleWhileMovebackward", 139);
  run_test(test_motor_control_withNoLeftObstacleWhileMovebackward, "test_motor_control_withNoLeftObstacleWhileMovebackward", 155);
  run_test(test_motor_control_withNoRightObstacleWhileMovebackward, "test_motor_control_withNoRightObstacleWhileMovebackward", 170);

  CMock_Guts_MemFreeFinal();
  return UnityEnd();
}
